services:
  java-aws-lambda-service:
    build: .
    hostname: lambda
    container_name: lambda-test
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    environment:
      - MONGO_DATABASE=local
      - MONGO_URI=mongodb://host.docker.internal:27017/
#      - MONGO_URI=mongodb://mongo:27017/
#    Use mongo URI according to your preference
    restart: on-failure
    networks:
      - lambda-network

  mongo:
    image: mongo:6.0.10
    hostname: mongo
    container_name: mongo-lambda
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      retries: 3
    ports:
      - "27017:27017"
    networks:
      - lambda-network

networks:
  lambda-network:
    driver: bridge
